// <auto-generated />
using BugTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BugTracker.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180524143813_projectAndBugImprovements")]
    partial class projectAndBugImprovements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("BugTracker.Models.Bug", b =>
                {
                    b.Property<long>("BugID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("StoryPoints");

                    b.HasKey("BugID");

                    b.ToTable("bugs");
                });
#pragma warning restore 612, 618
        }
    }
}
